version: '3'

services:
  datasolutionengineerexercise:
    image: datasolutionengineerexercise:latest

    volumes:
      - ./airflow:/opt/airflow
    
    ports:
      - "8080:8080"
    
    command: airflow standalone